version: 2

sources:
  - name: staging
    database: sage-now-339201
    schema: ny_taxi

    tables:
      - name: green_tripdata_external
      - name: yellow_tripdata_external
      - name: fhv_data_external
      - name: zones